[package]
name = "k8sec"
version = "0.1.0"
authors = ["betim.shala <betim_sh97@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"